// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: protos/crawler/crawler.proto

package crawler

import (
	context "context"
	fmt "fmt"
	math "math"
	
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CrawlerMaster service

func NewCrawlerMasterEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		{
			Name:    "CrawlerMaster.AddResource",
			Path:    []string{"/crawler/resource"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "CrawlerMaster.DelResource",
			Path:    []string{"/crawler/resource"},
			Method:  []string{"DELETE"},
			Body:    "*",
			Handler: "rpc",
		},
	}
}

// Client API for CrawlerMaster service

type CrawlerMasterService interface {
	AddResource(ctx context.Context, in *ResourceSpec, opts ...client.CallOption) (*NodeSpec, error)
	DelResource(ctx context.Context, in *ResourceSpec, opts ...client.CallOption) (*emptypb.Empty, error)
}

type crawlerMasterService struct {
	c    client.Client
	name string
}

func NewCrawlerMasterService(name string, c client.Client) CrawlerMasterService {
	return &crawlerMasterService{
		c:    c,
		name: name,
	}
}

func (c *crawlerMasterService) AddResource(ctx context.Context, in *ResourceSpec, opts ...client.CallOption) (*NodeSpec, error) {
	req := c.c.NewRequest(c.name, "CrawlerMaster.AddResource", in)
	out := new(NodeSpec)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerMasterService) DelResource(ctx context.Context, in *ResourceSpec, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "CrawlerMaster.DelResource", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CrawlerMaster service

type CrawlerMasterHandler interface {
	AddResource(context.Context, *ResourceSpec, *NodeSpec) error
	DelResource(context.Context, *ResourceSpec, *emptypb.Empty) error
}

func RegisterCrawlerMasterHandler(s server.Server, hdlr CrawlerMasterHandler, opts ...server.HandlerOption) error {
	type crawlerMaster interface {
		AddResource(ctx context.Context, in *ResourceSpec, out *NodeSpec) error
		DelResource(ctx context.Context, in *ResourceSpec, out *emptypb.Empty) error
	}
	type CrawlerMaster struct {
		crawlerMaster
	}
	h := &crawlerMasterHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "CrawlerMaster.AddResource",
		Path:    []string{"/crawler/resource"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "CrawlerMaster.DelResource",
		Path:    []string{"/crawler/resource"},
		Method:  []string{"DELETE"},
		Body:    "*",
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&CrawlerMaster{h}, opts...))
}

type crawlerMasterHandler struct {
	CrawlerMasterHandler
}

func (h *crawlerMasterHandler) AddResource(ctx context.Context, in *ResourceSpec, out *NodeSpec) error {
	return h.CrawlerMasterHandler.AddResource(ctx, in, out)
}

func (h *crawlerMasterHandler) DelResource(ctx context.Context, in *ResourceSpec, out *emptypb.Empty) error {
	return h.CrawlerMasterHandler.DelResource(ctx, in, out)
}
