apiVersion: v1
kind: Service
metadata:
  name: crawler-master
  labels:
    app: crawler-master
spec:
  selector:
    app: crawler-master
  ports:
    - port: 8081
      name: http
    - port: 9091
      name: grpc