apiVersion: v1
kind: Service
metadata:
  name: crawler-worker
  labels:
    app: crawler-worker
spec:
  selector:
    app: crawler-worker
  ports:
    - port: 8080
      name: http
    - port: 9090
      name: grpc